// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOCc_JCDn6yZxTx5sd9hi1ddYPTbP5_0g',
    appId: '1:1095835292152:web:c1e349321a70967e10860d',
    messagingSenderId: '1095835292152',
    projectId: 'note-app-with-firebase-73c91',
    authDomain: 'note-app-with-firebase-73c91.firebaseapp.com',
    storageBucket: 'note-app-with-firebase-73c91.firebasestorage.app',
    measurementId: 'G-E6K4W8FKT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJksuF8RH-Fpdprhubuy5i3NVp1ktbdg4',
    appId: '1:1095835292152:android:750a7df85ec21e9c10860d',
    messagingSenderId: '1095835292152',
    projectId: 'note-app-with-firebase-73c91',
    storageBucket: 'note-app-with-firebase-73c91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr-GJus6Fyr-zsFfp_wz-P4YKDDofxyjA',
    appId: '1:1095835292152:ios:e1f82f6dc1c1db3810860d',
    messagingSenderId: '1095835292152',
    projectId: 'note-app-with-firebase-73c91',
    storageBucket: 'note-app-with-firebase-73c91.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr-GJus6Fyr-zsFfp_wz-P4YKDDofxyjA',
    appId: '1:1095835292152:ios:e1f82f6dc1c1db3810860d',
    messagingSenderId: '1095835292152',
    projectId: 'note-app-with-firebase-73c91',
    storageBucket: 'note-app-with-firebase-73c91.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOCc_JCDn6yZxTx5sd9hi1ddYPTbP5_0g',
    appId: '1:1095835292152:web:fca05cf41480353b10860d',
    messagingSenderId: '1095835292152',
    projectId: 'note-app-with-firebase-73c91',
    authDomain: 'note-app-with-firebase-73c91.firebaseapp.com',
    storageBucket: 'note-app-with-firebase-73c91.firebasestorage.app',
    measurementId: 'G-BY23M6EKMT',
  );
}
